# Dockerfile.dev for the API

# Use the official Node.js 20 Alpine image as a base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# Install dependencies using npm
RUN npm install

# Copy the rest of the application's source code
COPY . .

# The NestJS app runs on port 3000 by default.
EXPOSE 3000

# The command to start the application in development mode (with hot-reloading)
CMD ["npm", "run", "start:dev"]